name: Different Mind Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
#      - name: Build OLM
#        run: |
#          apt update && apt -y install cmake build-essential
#          git clone https://gitlab.matrix.org/matrix-org/olm/
#          cd olm/
#          cmake . -Bbuild
#          make static
#          make
#          cp build/libolm.so* ../lib/
#          cp -r include/olm/ ../include/
#          cd ..
      - name: Run Build
        run: |
          go build -o matrix-bot
      - name: Create Artifact
        run: |
          mkdir build/
          mv matrix-bot build/
          mv plugins/ build/
          mv config.yaml.sample build/
      - uses: actions/upload-artifact@v2
        with:
          name: matrix-bot
          path: build/